apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-deleter
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: pod-deleter-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deleter-role-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: pod-deleter  # Replace with the service account name used by Argo Workflows if different
  namespace: argo
roleRef:
  kind: Role
  name: pod-deleter-role
  apiGroup: rbac.authorization.k8s.io
