apiVersion: v1
kind: Service
metadata:
  name: falco-metrics
  namespace: falco
  labels:
    app.kubernetes.io/instance: falco
spec:
  ports:
  - port: 8765
    targetPort: 8765
  selector:
    app.kubernetes.io/instance: falco
    app.kubernetes.io/name: falco
